# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 啊循
email: 308031396@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  温故可以知新
baseurl: "" # the subpath of your site, e.g. /blog
url: https://yangxun983323204.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  yangxun983323204
avatar: /assets/img/mir3.jpg
# favicon: /favicon.ico
favicon: /assets/img/ogp.png

#
# Icons
#
icons:
  rss: true
  email: 308031396@qq.com
  github: yangxun983323204
  bitbucket:
  twitter:
  facebook:
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram:
  linkedin: # full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: # full URL
  steam:
  wordpress:
  youtube:

#
# Prettify url.
#
permalink: pretty

#
# Scripts.
#
google_analytics: # e.g. UA-000000-01
disqus: false

#
# Localizations.
#
str_next: 下一页
str_prev: 上一页
str_read_more: 阅读更多...
str_search: 搜索
str_recent_posts: 最近文章
str_show_all_posts: 显示所有文章

#
# Recent posts.
#
recent_posts_num: 10

#
# Pagination.
#
paginate: 5
paginate_path: page/:num

#
# Social.
#
share_buttons:
  twitter: false
  facebook: false # needs ogp.fb.app_id
  hatena: false
ogp:
  image_url: //yangxun983323204.github.io/assets/img/mir3.jpg
  fb:
    admin: # facebook admin id
    app_id: # facebook application id

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji

include: ["_pages"]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - TestLocally.bat
